version: '3'

services:
  react:
    build:
      context: react
      dockerfile: Dockerfile
      args:
        - NPM_TOKEN
    environment:
      NODE_ENV: staging
    ports:
      - 3001:3001
  api:
    build:
      context: api
      dockerfile: Dockerfile
      args:
        - NPM_TOKEN
    volumes:
      - ./api/src/:/home/node/api/src
      - ./api/config/:/home/node/api/config
      - ./api/contracts/:/home/node/api/contracts
    environment:
      NODE_ENV: staging
      NODE_PATH: .
    networks:
      - main
    ports:
      - 3000:3000
    depends_on:
      - parity
  parity:
    image: appliedblockchain/parity-solo-instant:latest
    entrypoint: ["/parity/parity", "--config", "/solo/node.toml", "--unsafe-expose", "--gasprice", "1"]
    restart: always
    volumes:
      - parity:/solo/chains
    ports:
      - 8545:8545
      - 8546:8546
    networks:
      - main
volumes:
  parity:
networks:
  main:
